name: My First Github action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-nodev2
        with:
          node-version: '14.17.2'
      - run: node -v